sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t naoleyrashmi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true naoleyrashmi/docker-react npm run test
  #- docker run -e CI=true naoleyrashmi/Docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-098416882121"
  bucket_ path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: \AWS-ACCESS-KEY
  secret_access-key:
    secure: \$AWS_SECRET-KEY
