sudo :required
language: generic

services: 
  - docker

before_install:
  - docker build -t naoleyrashmi/Docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true naoleyrashmi/Docker-react npm run test
  #- docker run -e CI=true naoleyrashmi/Docker-react npm run test



